# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2021 Dimpact
# Generated by Django 2.2.24 on 2021-12-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenten", "0003_auto_20200124_1021"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enkelvoudiginformatieobject",
            name="indicatie_gebruiksrecht",
            field=models.NullBooleanField(
                default=False,
                help_text="Indicatie of er beperkingen gelden aangaande het gebruik van het informatieobject anders dan raadpleging. Dit veld mag `null` zijn om aan te geven dat de indicatie nog niet bekend is. Als de indicatie gezet is, dan kan je de gebruiksrechten die van toepassing zijn raadplegen via de GEBRUIKSRECHTen resource. Standaard waarde is `False`",
                verbose_name="indicatie gebruiksrecht",
            ),
        ),
    ]
