# SPDX-License-Identifier: EUPL-1.2
# Copyright (C) 2022 Dimpact
# Generated by Django 2.2.25 on 2022-01-17 16:26

from django.db import migrations, models
import vng_api_common.fields


class Migration(migrations.Migration):

    dependencies = [
        ("autorisaties", "0006_auto_20210323_1613"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unieke naam van de rol", max_length=255, unique=True
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Gebruikersvriendelijke naam van de rol",
                        max_length=255,
                    ),
                ),
                (
                    "zaaktype",
                    models.URLField(
                        blank=True,
                        help_text="URL naar het zaaktype waarop de autorisatie van toepassing is.",
                        max_length=1000,
                        verbose_name="zaaktype",
                    ),
                ),
                (
                    "max_vertrouwelijkheidaanduiding",
                    vng_api_common.fields.VertrouwelijkheidsAanduidingField(
                        blank=True,
                        choices=[
                            ("openbaar", "Openbaar"),
                            ("beperkt_openbaar", "Beperkt openbaar"),
                            ("intern", "Intern"),
                            ("zaakvertrouwelijk", "Zaakvertrouwelijk"),
                            ("vertrouwelijk", "Vertrouwelijk"),
                            ("confidentieel", "Confidentieel"),
                            ("geheim", "Geheim"),
                            ("zeer_geheim", "Zeer geheim"),
                        ],
                        help_text="Maximaal toegelaten vertrouwelijkheidaanduiding (inclusief).",
                        max_length=20,
                    ),
                ),
            ],
            options={"verbose_name": "rol", "verbose_name_plural": "rollen",},
        ),
    ]
